---
- name: Check if iperf3 is running
  ansible.builtin.command: pgrep -x iperf3
  register: iperf3_running
  changed_when: false
  failed_when: false

- name: Start iperf3 server
  ansible.builtin.command:
    cmd: iperf3 -s -D --pidfile /var/run/iperf3.pid
  when: iperf3_running.rc != 0
  changed_when: true
